Adding --no-post-hooks to bypass post hooks.
git-ftp/git-ftp pull request #664
Opened 2024-09-21 17:22 UTC by davidwebca

Add option to bypass post hooks just like the --no-verify option allows to bypass pre hooks which I needed for a specific use case. EXECUTE_HOOKS could be renamed to EXECUTE_PRE_HOOKS for specificity, but I didn't want to break any code that could use it unbeknownst to me.

2024-09-21 19:19 UTC, LukasFritzeDev requested changes
Thanks a lot for your addition. I think this feature is a useful enhancement.

And I like your suggestion to rename `EXECUTE_HOOKS` to `EXECUTE_PRE_HOOKS`.  As long as the flag keeps the same name, I think we can (and should) do this. This variable is not part of the public interface of the tool., it’s only used for internal state handling.

And it would be great if you could add documentation about this feature in the [tool manual](https://github.com/davidwebca/git-ftp/blob/patch-1/man/git-ftp.1.md). The flag should be listed in the [section Options](https://github.com/davidwebca/git-ftp/blob/patch-1/man/git-ftp.1.md#options) and I’d recommend an additional note in the last paragraph of the [section Hooks](https://github.com/davidwebca/git-ftp/blob/patch-1/man/git-ftp.1.md#hooks-experimental)

2024-09-21 21:05 UTC, davidwebca commented
Will do later tonight! 🤘

2024-10-09 23:44 UTC, davidwebca commented
Alright, just remembered about this, sorry I had forgotten (not me saying "will do later tonight" 🤦‍♂️ ). I just pushed changes and small additions to the docs. Let me know if you need anything else!

2024-10-20 16:29 UTC, LukasFritzeDev approved these changes
Thanks for your work and for adding the documentations. Looks good to me.

2024-10-20 16:29 UTC, merged